[graph]
targets = [
    { triple = "wasm32-wasip1" },
]

[advisories]
version = 2
yanked = "deny"
ignore = [
    # proc-macro-error is unmaintained, but it is required by zellij-tile
    "RUSTSEC-2024-0370",
    # atty is unmaintained, but it is required by zellij-tile
    "RUSTSEC-2024-0375",
    # atty vuln that only affects windows
    "RUSTSEC-2021-0145",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    # these duplicate dependencies all come from zellij-tile
    { name = "vte", version = "0.10.1" },
    { name = "vte", version = "0.11.1" },
    { name = "syn", version = "1.0.109" },
    { name = "syn", version = "2.0.95" },
    { name = "indexmap", version = "1.9.3" },
    { name = "indexmap", version = "2.7.0" },
    { name = "heck", version = "0.3.3" },
    { name = "heck", version = "0.4.1" },
    { name = "hashbrown", version = "0.12.3" },
    { name = "hashbrown", version = "0.15.2" },
    { name = "bitflags", version = "1.3.2" },
    { name = "bitflags", version = "2.6.0" },
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
]
